# Global Configurations
global:
  scrape_interval:     50s
  evaluation_interval: 50s

  external_labels:
      monitor: 'elixir_sample_app'

# Targets to scrape
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app'
    static_configs:
      - targets: ['localhost:4000']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
